### ISSUE TITLE
Running under Singularity

### ISSUE THREAD

**Issue by sneumann** [ProteoWizard/container#1]
Hi, I tried running under Singularity, as we have NFS and docker is difficult there.
Conversion turned out to be quite easy with 
`docker run -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/singularity/:/output --privileged -t --rm   singularityware/docker2singularity chambm/pwiz-skyline-i-agree-to-the-vendor-licenses`

But the issue is that inside the singularity container, the uid is that of the outside user. 
Even with the `sudo` approach I was not successful:
```
Singularity chambm_pwiz-skyline-i-agree-to-the-vendor-licenses-2019-05-10-2215f51c69fd.simg:/tmp/singularity> /usr/bin/wine64_anyuser msconvert
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
```
Instead I have a PR in the works that has a lightweight approach to create a personal $WINEPREFIX.
Yours, Steffen

**Comment by devin-encodia** [comment]
Hi I'm still having root issues here. Can you link me to the singularity image for skyline or the updated docker image that can be converted to singularity? 

I ran "singularity build" to build the .sif image from the docker image, then tried to run the container via "singularity run". 

I'm getting the following error: 
>>sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

Thanks, 
Devin

**Comment by sneumann** [comment]
Hi Devin, can you elaborate and give more context for the error ? I am unsure where sudo is called, what it is calling, and which filesystem the error refers to. Yours, Steffen

**Comment by devin-encodia** [comment]
Hi Steffen, 

Thanks for the reply! 

After pulling the docker image, I'm using:
`>> singularity build skyline_v0_0.0.1.sif docker-daemon://chambm/pwiz-skyline-i-agree-to-the-vendor-licenses:latest`

This builds just fine, but when trying to run the singularity image, it yields:
`>> singularity run ./skyline_v0_0.0.1.sif`
` sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?`

Not that it should matter in the container, but I'm running from Ubuntu 20.04 and I can run other singularity images built from Docker on the system.

**Comment by sneumann** [comment]
Hi, I can't tell if my invocation is the most elegant, the following is what I use:
```
singularity exec -B /path/to/your/data/:/data -B `mktemp -d /dev/shm/wineXXX`:/mywineprefix /path/to/images/chambm_pwiz-skyline-i-agree-to-the-vendor-licenses-2019-05-23-1c92fb5c2527.simg mywine msconvert --32 /data/brukerexampledata.d
```
I also know that M. Bernt in the Galaxy community is successfully using msconvert under wine,
they also might have a working incantation. 
Yours, Steffen

**Comment by jspaezp** [comment]
Hello @sneumann 

I tried your method by using...

```
singularity exec -B ${MYPATH}/:/data -B `mktemp -d /dev/shm/wineXXX`:/mywineprefix docker://chambm/pwiz-skyline-i-agree-to-the-vendor-licenses:x64 mywine msconvert /data/MYFILE.raw
```

And I get...

```
INFO:    Using cached SIF image
wine: configuration in '/mywineprefix' has been updated.
format: mzML 
    m/z: Compression-None, 64-bit
    intensity: Compression-None, 32-bit
    rt: Compression-None, 64-bit
ByteOrder_LittleEndian
 indexed="true"
outputPath: .
extension: .mzML
contactFilename: 
runIndexSet: 

spectrum list filters:
  
chromatogram list filters:
  
filenames:
  /data\MYFILE.raw
  
processing file: /data\MYFILE.raw
[C:\pwiz\msconvert.exe] Caught unknown exception.
Please report this error to support@proteowizard.org.
Attach the command output and this version information in your report:

ProteoWizard release: 3.0.20287 (769529fa4)
Build date: Oct 13 2020 23:37:03
```

... have you encountered this error in the past? `[C:\pwiz\msconvert.exe] Caught unknown exception.` is not the most informative error message out there to debug ...

Kindest wishes,
Sebastian

(just as a side note, running the same command in the native docker implementation does work on the same file, by copying the file to my local computer running `docker run -it --rm -e WINEDEBUG=-all -v ${DATA_PATH}/:/data chambm/pwiz-skyline-i-agree-to-the-vendor-licenses wine msconvert.exe /data/{MYFILE}.raw`, so file integrity is not the issue)

**Comment by rsdmse** [comment]
I'm getting the exact same error with a .raw file using the latest image:
```
ProteoWizard release: 3.0.21258 (ae984af)
Build date: Sep 15 2021 00:51:54
```

**Comment by sneumann** [comment]
Hi, does that happen with all `*.raw` files ? Can you try with soem from other (older) instruments, maybe some from e.g.
https://www.ebi.ac.uk/pride/archive/projects/PXD005011 or http://ftp.pride.ebi.ac.uk/pride/data/archive/2018/04/PXD005011/ ? Then we see if it is the container or your raw data. Yours, Steffen

**Comment by rsdmse** [comment]
Thanks for the suggestion. I tried the first *.raw file in the second link and got the same error:
```
$singularity exec -B .:/data -B `mktemp -d /dev/shm/wineXXX`:/mywineprefix pwiz-skyline-i-agree-to-the-vendor-licenses_latest.sif mywine msconvert  /data/OTNCS25cm_GG01_C1-1.raw 
wine: configuration in '/mywineprefix' has been updated.
format: mzML 
    m/z: Compression-None, 64-bit
    intensity: Compression-None, 32-bit
    rt: Compression-None, 64-bit
ByteOrder_LittleEndian
 indexed="true"
outputPath: .
extension: .mzML
contactFilename: 
runIndexSet: 

spectrum list filters:
  
chromatogram list filters:
  
filenames:
  /data\OTNCS25cm_GG01_C1-1.raw
  
processing file: /data\OTNCS25cm_GG01_C1-1.raw
[C:\pwiz\msconvert.exe] Caught unknown exception.
Please report this error to support@proteowizard.org.
Attach the command output and this version information in your report:

ProteoWizard release: 3.0.21258 (ae984af)
Build date: Sep 15 2021 00:51:54
```
I also tried without bindmounting to `/data`. I checked that there are no issues with running `mktemp -d /dev/shm/wineXXX`.

**Comment by sneumann** [comment]
I can confirm the above issue. this is on singularity `3.5.2+ds1-1` It could be that I created the above invocation before the 3.X series, and some behavior had changed. The idea behind the `/mywineprefix` is that wine needs a `WINEPREFIX` owned by the user (so it can't be created inside the image, and it might also be impossible to `chown` it during runtime). Using `/dev/shm/*` was so that it gets cleaned up afterwards. Yours, Steffen

**Comment by sneumann** [comment]
Hi, I now found my updated invocation, and I guess ` --writable-tmpfs ` is what solves the issue at hand. Yours, Steffen
```
IMAGE=chambm_pwiz-skyline-i-agree-to-the-vendor-licenses-2019-05-23-1c92fb5c2527.simg
TMPMYWINEPREFIX=`mktemp -d /dev/shm/wineXXX`

  singularity exec \
    --cleanenv \
    -B "$OUTDIR":/data \
    -B $TMPMYWINEPREFIX:/mywineprefix \
    --writable-tmpfs \
    "$IMAGE" \
    mywine msconvert \
    --32 --zlib --filter "peakPicking true 1-" --filter "zeroSamples removeExtra" \
    --outdir  z:/data/mzML \
    "z:/data/$FILE"

   sleep 2 ; rmdir $TMPMYWINEPREFIX
```

**Comment by tiwars46** [comment]
Hi, i am getting this error when running msconvert using singularity: 

```
singularity shell -B /pathtomydata/:/data -B `mktemp -d /dev/shm/wineXXX`:/mywineprefix  pwiz-skyline-i-agree-to-the-vendor-licenses_latest.sif

mywine msconvert /pathtomydata/01709a_GA1-TUM_first_pool_99_01_01-DDA-1h-R1.raw --32 --zlib --filter "peakPicking true 1-" --filter "zeroSamples removeExtra" --outdir  /pathtomydata/ --mzML

processing file: /data\rawfilename.raw
[RawFileImpl::getInstrumentMethods()] Access to the path 'C:\users\root\Temp\tmp6b58.tmp' is denied.
Error processing file /data\rawfilename.raw

```

**Comment by jspaezp** [comment]
@tiwars46 check this https://github.com/ProteoWizard/pwiz/issues/2387#issuecomment-1320984700

This is the only thing i could do to make it work in my cluster

**Comment by d0minicO** [comment]
I have the same error as tiwars46. Would love a solution!

**Comment by sneumann** [comment]
Hi @d0minicO , does https://github.com/ProteoWizard/pwiz/issues/2387#issuecomment-1323875346 help in any way ? Yours, Steffem

**Comment by tiwars46** [comment]
Hi @jspaezp thanks for the link. I followed all the steps you mentioned and it worked for me on my cluster. Thanks again.

**Comment by jspaezp** [comment]
@tiwars46 you are more than welcome, i know it took me a while to figure it out ...

**Comment by d0minicO** [comment]
Hi @sneumann I followed the advice of @jspaezp and it seems to be working for me now. If for some reason it stops working I will use your suggested method! Thanks all
