### ISSUE TITLE
Running docker msconvert under Singularity

### ISSUE THREAD

**Issue by achucode** [ProteoWizard/container#13]
Dear all,

I'm well aware that singularity is not supported, and I'm afraid I'll reactivate a closed thread, but I just hope somebody out there may be able to give me some pointers. 

I'm trying to run msconvert on Thermo raw files on a linux machine using singularity. The docker solution works absolutely fine on this machine, but I need to prepare the field for moving on to a linux cluster where docker is not allowed. 

The linux machine (an Ubuntu 20.04) has the following installed:

singularity-ce version 3.9.3-focal 
Docker version 20.10.12, build e91ed57
ProteoWizard release: 3.0.21354 (9ee14c7); Build date: Dec 20 2021 16:00:06

As an example of a raw file, one can use for instance OTNCS25cm_GG01_UG3-5.raw from the PRIDE archive ftp.ebi.ac.uk/pride-archive/2018/04/PXD005011.

When I do

docker run -it --rm -e WINEDEBUG=-all -v /path/to/Data:/data chambm/pwiz-skyline-i-agree-to-the-vendor-licenses wine msconvert /data/OTNCS25cm_GG01_UG3-5.raw

I get as expected an mzML file in return. So far so good, as I said the docker solution works for me.

I then built a singularity image with

singularity build msconvert.sif docker://chambm/pwiz-skyline-i-agree-to-the-vendor-licenses

and run it as

singularity exec --cleanenv -B /path/to/Data:/data -B `mktemp -d /dev/shm/wineXXX`:/mywineprefix --writable-tmpfs  /path/to/Data/msconvert.sif mywine msconvert /data/OTNCS25cm_GG01_UG3-5.raw

then I get the following error:
----------------------------------
wine: configuration in '/mywineprefix' has been updated.
format: mzML 
    m/z: Compression-None, 64-bit
    intensity: Compression-None, 32-bit
    rt: Compression-None, 64-bit
ByteOrder_LittleEndian
 indexed="true"
outputPath: .
extension: .mzML
contactFilename: 
runIndexSet: 

spectrum list filters:
  
chromatogram list filters:
  
filenames:
  /data\OTNCS25cm_GG01_UG3-5.raw
  
processing file: /data\OTNCS25cm_GG01_UG3-5.raw
[C:\pwiz\msconvert.exe] Caught unknown exception.
Please report this error to support@proteowizard.org.
Attach the command output and this version information in your report:

ProteoWizard release: 3.0.21354 (9ee14c7)
Build date: Dec 20 2021 16:00:06

----------------------------------

If instead of a raw file I feed it an mgf file (or any files that does not requires msconvert to access the wine dll libraries), then I get the correct and expected output.

I'm gratefully taking in any ideas...

Thanks and best wishes,
AChU

**Comment by chambm** [comment]
Try `singularity exec -B /path/to/Data:/data -S /mywineprefix/ msconvert_cont mywine msconvert /data/OTNCS25cm_GG01_UG3-5.raw`

**Comment by achucode** [comment]
Thank you for your reply. When I type the command you suggest, I get a pop up window from wine (see attached screenshot) warning me that "rundll32.exe: this application could not be started". On the command line I still get I'm afraid the same error message as before ( "C:\pwiz\msconvert.exe] Caught unknown exception").
![Screenshot_2022-01-21_16-06-18](https://user-images.githubusercontent.com/57526675/150551458-bccd3c51-59e4-4b5e-96c2-e73724cbf128.png)

Does this suggest something to you? Thanks again

**Comment by chambm** [comment]
Hi @achucode sorry I didn't have any further ideas on this. Did you ever find a solution?

**Comment by achucode** [comment]
I was suggested the following workaround, which did actually work for me, both on a mini linux mint server and a HPC CentOS cluster, and on Thermo RAW files: one essentially needs to have a user access to the wineprefix directory included in the image, and this can be achieved by taking this  directory out of the image, and copying it over to one's home directory. 

These are the instructions I got forwarded:

# How to create and use the singularity container:
1. create the singularity container:
          A. requires a linux machine with root access and singularity installed
          B. Convert the docker image into a singularity one

                  singularity pull docker://chambm/pwiz-skyline-i-agree-to-the-vendor-licenses

(notes from achucode: I don't think you need root...)

2. Prepare and use the singularity container
          A. The winprefix64 directory has to be removed if it already exists in the folder that contains the image
          B. We make a copy of the winprefix64 folder included in the container
          C. (OPTINAL): Make the winprefix64 directory readable and writable by the group
          D. Run the container

                  rm -rf wineprefix64
                  singularity shell singularity/pwiz-skyline-i-agree-to-the-vendor-licenses_latest.sif
                  cp -r /wineprefix64 . # that command displays errors that should not be problematic)
                  exit # exit the container

                  find wineprefix64/ -type d -exec chmod 770 {} \; # change directories permissions
                  find wineprefix64/ -type f -exec chmod 660 {} \; # change files permissions

                  # run msconvert:
                  singularity exec -B wineprefix64:/wineprefix64 ./pwiz-skyline-i-agree-to-the-vendor-licenses_latest.sif wine msconvert 

So not the most elegant solution, especially since the wineprefix directory is easily 5-6 GB, but at least msconvert seemed to find at last the thermo libraries!

Best wishes,
AChU

**Comment by chambm** [comment]
Interesting. I'm not surprised that the wineprefix needs to be writeable by Wine. Otherwise it'd be like expecting Windows to work if the Windows directory was read-only. I'm glad you got it working.
