### ISSUE TITLE
RawFileImpl::getInstrumentMethods() error

### ISSUE THREAD

**Issue by linsherpa** [ProteoWizard/container#19]
while converting the raw file (from Thermo scientific orbitrap LC_MS) in to mzML file i faced the following error:

[RawFileImpl::getInstrumentMethods()] Access to the path "c:\users\root\Temp\tmp5d3a.tmp" is denied

Any idea how to resolve this?

**Comment by chambm** [comment]
Is this on a Windows machine? Is your username really "root"? If not I'm guessing you have a TMP or TEMP environment variable pointing at c:\users\root\temp and your user doesn't have access to it.

**Comment by linsherpa** [comment]
Actually I am using a linux machine
ill have a look at the image.

**Comment by chambm** [comment]
So you're using the pwiz-skyline docker image?

**Comment by charlin90** [comment]
I have same issue as @linsherpa

**Comment by linsherpa** [comment]
@chambm yes

**Comment by linsherpa** [comment]
@chambm : the same docker image works for Raw file from another vendors, except for the raw file (from Thermo scientific orbitrap LC_MS)

**Comment by chambm** [comment]
Does it fail on every Thermo RAW you try, or just some?

**Comment by linsherpa** [comment]
so far i have tried three of them, all same issue

**Comment by chambm** [comment]
What Docker command are you using?

**Comment by linsherpa** [comment]
wine64_anyuser msconvert <filename>

where
wine64_anyuser is equivalent to "sudo -E -H -u root wine64"

**Comment by chambm** [comment]
Have you tried without the _anyuser wrapper?

**Comment by linsherpa** [comment]
I tried.. just now .. same issue
filenames:
  /var/lib/cwl/stg49f806ec-8be3-4c78-a207-9f78c1d5cbcf\File030.raw
  
processing file: /var/lib/cwl/stg49f806ec-8be3-4c78-a207-9f78c1d5cbcf\File030.raw
[RawFileImpl::getInstrumentMethods()] Access to the path 'C:\users\root\Temp\tmp7a2b.tmp' is denied.
Error processing file /var/lib/cwl/stg49f806ec-8be3-4c78-a207-9f78c1d5cbcf\File030.raw

**Comment by chambm** [comment]
And what's the full docker and msconvert command, not just the wine64 part?

**Comment by linsherpa** [comment]
I am actually using a cwl- a workflow tool (https://www.commonwl.org/) that uses docker (the image pwiz-skyline...). But using a normal command should also result the same issue.
(P.S: I am using a linux system)

In addition: it seems this challenge has been incurred before too.
https://github.com/ProteoWizard/container/issues/1#issuecomment-1311793888

**Comment by chambm** [comment]
That was using singularity instead of docker. That's why I asked for the full docker command. What CWL workflow? Is it public?

**Comment by linsherpa** [comment]
the full equivalent docker command will be 
docker \
    run \
    -i \
    --mount=type=bind,source=/tmp/z4n1fp6o,target=/axiDbF \
    --mount=type=bind,source=/tmp/ugnaoefd,target=/tmp \
    --mount=type=bind,source=/home/lincoln/Documents/NFDI4Chem/project_file/cwl_converter_test/example_file/File030.raw,target=/var/lib/cwl/stg49f806ec-8be3-4c78-a207-9f78c1d5cbcf/File030.raw,readonly \
    --workdir=/axiDbF \
    --read-only=true \
    --net=none \
    --user=0:0 \
    --rm \
    --cidfile=/tmp/w9arin73/20230524165202-940169.cid \
    --env=TMPDIR=/tmp \
    --env=HOME=/axiDbF \
    lincoln1010/test_temp_permission \
    wine64 \
    msconvert \
    /var/lib/cwl/stg49f806ec-8be3-4c78-a207-9f78c1d5cbcf/File030.raw \
    mzML


PS: lincoln1010/test_temp_permission image is same as chambm/pwiz-....

**Comment by chambm** [comment]
Can you take off the read-only? I don't think wine can use the Linux TMPDIR at /tmp. It needs to be under its Windows prefix and of course it needs to be writeable.

**Comment by linsherpa** [comment]
i checked the same files by running a container with shared volume (using the pwiz...image). It works.
That means i need to have a look on my workflow 
Thank you for your support
