### ISSUE TITLE
[Error 13] Permission denied: "desktop-directories"

### ISSUE THREAD

**Issue by linsherpa** [ProteoWizard/container#21]
I am using the command wine64_anyuser for a RAW file as nonroot user.
Here the wine64_anyuser is equivalent to 
sudo -E -u root wine64 "$@"

Docker full command (at the bottom)

This has resulted in the error --PermissionError:[Error 13] Permission denied: "desktop-directories"
SOLUTION:
I have tried adding  "-H" in this command as well
sudo -E -H -u root wine64 "$@"

It works.

**Docker command :**

docker \
    run \
    -i \
    --mount=type=bind,source=/tmp/icry4fgp,target=/JErBuM \
    --mount=type=bind,source=/tmp/x67nsbq3,target=/tmp \
    --mount=type=bind,source=/home/lincoln/Documents/NFDI4Chem/project_folder/mass_spectrometry_file_converter_ver2-main/example_file/File014.RAW,target=/var/lib/cwl/stge7bf95f9-b98f-4bb4-ba4e-c78450e672ba/File014.RAW,readonly \
    --workdir=/JErBuM \
    --net=none \
    --user=1000:1000 \
    --rm \
    --cidfile=/tmp/u73vkd4a/20230616183645-624691.cid \
    --env=TMPDIR=/tmp \
    --env=HOME=/JErBuM \
    chambm/pwiz-skyline-i-agree-to-the-vendor-licenses \
    wine64_anyuser \
    msconvert \
    /var/lib/cwl/stge7bf95f9-b98f-4bb4-ba4e-c78450e672ba/File014.RAW \
    mzML

**Comment by chambm** [comment]
Fix with your PR, thanks!
