### ISSUE TITLE
Question: Relation to Docker images

### ISSUE THREAD

**Issue by fkromer** [ProteoWizard/container#6]
According to this [Dockerfile](https://github.com/ProteoWizard/container/blob/master/dotnet/Dockerfile) I guess this repository relates to the [chambm/wine-dotnet](https://hub.docker.com/r/chambm/wine-dotnet) and due to this [Dockerfile](https://github.com/ProteoWizard/container/blob/master/Dockerfile) to the Docker image [chambm/pwiz-skyline-i-agree-to-the-vendor-licenses](https://hub.docker.com/r/chambm/pwiz-skyline-i-agree-to-the-vendor-licenses) as well. Is this correct?

**Comment by chambm** [comment]
Yes, it was surprisingly hard to get .NET 4.7.2 working with Wine 64-bit. Once I did, I didn't want to have to keep rebuilding it whenever pwiz changed!
